import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

// Use the Lato font
const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato", // Optional: for Tailwind/CSS variable usage
  weight: ["400", "700"], // or "100" to "900", depending on what you need
});

export const metadata: Metadata = {
  title: "Cinema",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lato.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
